name: Setup

runs:
  using: composite

  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 
    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn --immutable
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'