[profile.default]
src = 'contracts'
out = 'build'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
fs_permissions = [{ access = "read", path = "./"}]
via_ir = true
optimizer = true
optimizer_runs = 200

# For testing we remove some optimizations to make it faster
[profile.test]
optimizer = false
optimizer_runs = 1

[profile.test.optimizer_details.yulDetails]
optimizer_steps = ':'