[profile.default]
src = 'contracts'
out = 'build'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
optimizer = true
optimizer-runs = 200
via_ir = true

[profile.lite]
optimizer = false
optimizer-runs = 1

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ':'