name: CI - packages/subgraph-service

env:
  CI: true

on:
  push:
    branches: "*"
    paths:
      - packages/subgraph-service/**
  pull_request:
    branches: "*"
    paths:
      - packages/subgraph-service/**
  workflow_dispatch:

jobs:
  test-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: |
          pushd packages/subgraph-service
          yarn build
      - name: Run tests
        run: |
          pushd packages/subgraph-service
          yarn test