name: CI

env:
  CI: true

on:
  push:
    branches: [main]
    paths:
      - packages/contracts/**
  pull_request: {}


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Run tests
        run: yarn test:coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          flags: unittests
          name: graphprotocol-contracts
          fail_ci_if_error: true
